### ISSUE TITLE
Generate good sample data for testing and demos

### ISSUE THREAD

**Issue by mikera** [DEX-Company/surfer#105]

**Comment by pedrorgirardi** [comment]
We've implemented two new functions `surfer.asset/import!` and `surfer.asset/import-edn!` to read a `datasets.edn` file with the path and metadata of assets to import. 

It can be used from the REPL: there's a form inside `comment` (in `dev`) to import the datasets. And there's also a new HTTP endpoint to do it: `/api/v1/market-admin/import-datasets`.

It's a basic implementation, but it makes importing datasets easier.

#### `datasets.edn`

```clojure
{"datasets/glossary.md"
 {:name "DEP Glossary"
  :description "This Glossary provides definitions of common terms used in DEPs"
  :type "dataset"
  :contentType "text/markdown"
  :enconding "UTF-8"
  :dataCreated "2019-07-21"
  :creator "Mike Anderson"
  :license "Copyright (c) 2019 DEX Pte. Ltd."
  :inLanguage "en"
  :tags ["dex" "dep"]
  :links [{:name "GitHub"
           :url "https://github.com/DEX-Company/DEPs/tree/master/0"}]}}
```

![Screen Shot 2019-12-03 at 7 41 09 AM](https://user-images.githubusercontent.com/585191/70006582-4da79380-15a0-11ea-8fb7-78547f6f39bf.png)
