### ISSUE TITLE
Orchestration

### ISSUE THREAD

**Issue by pedrorgirardi** [DEX-Company/surfer#124]
a special kind of operation
the source code is execution graph
composed execution
produces provenance
process flow execution engine 
how does this link back to jobs ? i.e. the display of job output ?

**Comment by mikera** [comment]
Standard is outlined in DEP13 - https://github.com/DEX-Company/DEPs/tree/master/13

**Comment by pedrorgirardi** [comment]
- [ ] DEP 13 Data Format specs and tests
- [ ] Invoke API - Add Orchestration support
- [ ] Redirect Orchestration's parameters to Operation's parameters
- [ ] Redirect Operation's results to Orchestration's results
- [ ] Format Orchestration's execution output to DEP 13 format
- [ ] Demos
