### ISSUE TITLE
Upload asset on Surfer returns a 500 Server error

### ISSUE THREAD

**Issue by shark8me** [DEX-Company/surfer#82]
Steps to reproduce:

Run `lein test :only integration.surfer-test` on starfish-clj. There are no exceptions or messages printed on Surfer `log/surfer.log` or on the console

The upload asset test returns an error:

--

ERROR in (register-with-surfer) (RemoteAgent.java:501)
Uncaught exception, not in assertion.
expected: nil
  actual: sg.dex.starfish.exception.GenericException: Internal Server Error : HTTP/1.1 500 Internal Server Error
 at sg.dex.starfish.impl.remote.RemoteAgent.uploadAssetContent (RemoteAgent.java:501)
    sg.dex.starfish.impl.remote.RemoteAgent.uploadAsset (RemoteAgent.java:444)
    starfish.core$upload.invokeStatic (core.cljc:368)
    starfish.core$upload.invoke (core.cljc:365)
    integration.test_surfer$fn__808.invokeStatic (test_surfer.clj:30)
    integration.test_surfer/fn (test_surfer.clj:18)
    clojure.test$test_var$fn__9737.invoke (test.clj:717)
    clojure.test$test_var.invokeStatic (test.clj:717)
    clojure.test$test_var.invoke (test.clj:708)
    clojure.test$test_vars$fn__9763$fn__9768.invoke (test.clj:735)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    clojure.test$test_vars$fn__9763.invoke (test.clj:735)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    clojure.test$test_vars.invokeStatic (test.clj:731)
    clojure.test$test_all_vars.invokeStatic (test.clj:737)
    clojure.test$test_ns.invokeStatic (test.clj:758)
    clojure.test$test_ns.invoke (test.clj:743)
    user$eval224$fn__345.invoke (form-init2926605028244876544.clj:1)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.injected$compose_hooks$fn__154.doInvoke (form-init2926605028244876544.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.injected$run_hooks.invokeStatic (form-init2926605028244876544.clj:1)
    leiningen.core.injected$run_hooks.invoke (form-init2926605028244876544.clj:1)
    leiningen.core.injected$prepare_for_hooks$fn__159$fn__160.doInvoke (form-init2926605028244876544.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$map$fn__5866.invoke (core.clj:2755)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1792)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.test$run_tests.invokeStatic (test.clj:768)
    clojure.test$run_tests.doInvoke (test.clj:768)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    user$eval224$fn__357$fn__410.invoke (form-init2926605028244876544.clj:1)
    user$eval224$fn__357$fn__358.invoke (form-init2926605028244876544.clj:1)
    user$eval224$fn__357.invoke (form-init2926605028244876544.clj:1)
    user$eval224.invokeStatic (form-init2926605028244876544.clj:1)
    user$eval224.invoke (form-init2926605028244876544.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:7177)
    clojure.lang.Compiler.eval (Compiler.java:7167)
    clojure.lang.Compiler.load (Compiler.java:7636)
    clojure.lang.Compiler.loadFile (Compiler.java:7574)
    clojure.main$load_script.invokeStatic (main.clj:475)
    clojure.main$init_opt.invokeStatic (main.clj:477)
    clojure.main$init_opt.invoke (main.clj:477)
    clojure.main$initialize.invokeStatic (main.clj:508)
    clojure.main$null_opt.invokeStatic (main.clj:542)
    clojure.main$null_opt.invoke (main.clj:539)
    clojure.main$main.invokeStatic (main.clj:664)
    clojure.main$main.doInvoke (main.clj:616)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:40)

Ran 2 tests containing 5 assertions.
0 failures, 1 errors.
Tests failed.

**Comment by pedrorgirardi** [comment]
@shark8me I will close this one since upload tests are passing.
